name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout current repository to MAIN branch
        uses: actions/checkout@v3

      - name: Setup NodeJs 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Generate README file
        run: node .

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit and Push new README.md to the repository
        run: |
          git add .
          git commit -m "[GH ACTIONS] Update readme"
          git push origin main
